name: "Terraform Orchestrator"
description: "Automate Terraform workflows in GitHub Actions, including init, plan, apply, and validation."
author: "@andresb39"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  arg:
    description: "Arguments to be used with Terraform"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Pre-requirements
      run: bash ${{ github.action_path }}/cmd/pre-requirements.sh
      shell: bash
    - name: Terraform ${{ inputs.arg }}
      run: bash ${{ github.action_path }}/cmd/terraform.sh ${{ inputs.arg }}
      shell: bash
